### ISSUE TITLE
Delete custom word buttons

### ISSUE THREAD

**Issue by 54nn0n** [Patricia-NavarroMartin/TTS#2]
Add the functionality for the user to remove custom words

After deleting take care that we update the UI only by removing that specific button element (and word in category words)

UI idea:
Currently both fixed and custom words look the same. It may be good for the user to have a slight visual cue so that they know which words they can adjust themselves?

---

Solution:
Provide a menu when long-pressing a button. It will open a drawer coming in from the bottom.

![Image](https://github.com/Patricia-NavarroMartin/TTS/assets/85356105/edcb504c-d5c1-4b14-8637-c305b5a1151f)

```css
:root {
--spacing-l: 24px;
--error: #C62A2A;
}
``` 

```css
#drawer {
  background-color: var(--ui01);
  padding-top: var(--spacing-l);
  padding-bottom: var(--spacing-l);
  padding-left: var(--spacing-m);
  padding-right: var(--spacing-m);
  border-radius: var(--rounded); /*Only on the top-left and top-right */
}
``` 

```css
#destructiveButton {
background-color: var(--error);
color: white;
```
